# Markdownlint configuration for Quiz App
# See https://github.com/DavidAnson/markdownlint for more information

# Disable specific rules
MD013: false # Line length
MD033: false # Inline HTML
MD041: false # First line in a file should be a top-level heading
MD024: false # Multiple headings with the same content
MD026: false # Trailing punctuation in heading
MD007: # Unordered list indentation
  indent: 2
MD010: false # Hard tabs
MD012: false # Multiple consecutive blank lines
MD029: false # Ordered list item prefix
MD030: false # Spaces after list markers
MD046: false # Code block style
MD045: false # Images should have alternate text (alt text)
MD034: false # Bare URL used
MD036: false # Emphasis used instead of a heading
