"""Add created_by field to Survey model

Revision ID: 1997d659a814
Revises: d42dd0829508
Create Date: 2025-07-06 21:14:41.393538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1997d659a814'
down_revision = 'd42dd0829508'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_survey_created_by_user', 'user', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey', schema=None) as batch_op:
        batch_op.drop_constraint('fk_survey_created_by_user', type_='foreignkey')
        batch_op.drop_column('created_by')
    # ### end Alembic commands ###
