"""add_telegram_fields_to_userdata_model

Revision ID: 40358149e8ad
Revises: 5e3035c71896
Create Date: 2025-07-06 21:53:07.247655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40358149e8ad'
down_revision = '5e3035c71896'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userdata', sa.Column('telegram_user_id', sa.Integer(), nullable=True))
    op.add_column('userdata', sa.Column('telegram_username', sa.String(length=100), nullable=True))
    op.add_column('userdata', sa.Column('telegram_first_name', sa.String(length=100), nullable=True))
    op.add_column('userdata', sa.Column('telegram_last_name', sa.String(length=100), nullable=True))
    op.add_column('userdata', sa.Column('telegram_language_code', sa.String(length=10), nullable=True))
    op.add_column('userdata', sa.Column('telegram_photo_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userdata', 'telegram_photo_url')
    op.drop_column('userdata', 'telegram_language_code')
    op.drop_column('userdata', 'telegram_last_name')
    op.drop_column('userdata', 'telegram_first_name')
    op.drop_column('userdata', 'telegram_username')
    op.drop_column('userdata', 'telegram_user_id')
    # ### end Alembic commands ###
