"""add_question_data_field_to_question_model

Revision ID: 5e3035c71896
Revises: 1997d659a814
Create Date: 2025-07-06 21:49:06.418530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e3035c71896'
down_revision = '1997d659a814'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('question_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'question_data')
    # ### end Alembic commands ###
